### ISSUE TITLE
https support ?

### ISSUE THREAD

**Issue by mareban** [HatsuneMiku3939/fluent-plugin-http-pull#14]
Hello,

Nice plugin :-) !

Is HTTPS supported, and if it  is, how can we do HTTPS request please ?

Thanks for your help.

**Comment by HatsuneMiku3939** [comment]
Hello.
Thank you for using my plugin.

Of course, it also supports HTTPS. 
It can be done simply by using the HTTPS URL as shown below.

```
<source>
  @type http_pull

  tag test
  url https://www.google.com
  interval 1s

  format none
  status_only true
</source>

<match test>
  @type stdout
</match>

# 2018-05-23 18:46:04.999666252 +0900 test: {"url":"https://www.google.com","status":200}
# 2018-05-23 18:46:05.977556934 +0900 test: {"url":"https://www.google.com","status":200}
# 2018-05-23 18:46:06.981809246 +0900 test: {"url":"https://www.google.com","status":200}
# 2018-05-23 18:46:07.989011414 +0900 test: {"url":"https://www.google.com","status":200}
```

**Comment by mareban** [comment]
Hello,

Thanks for your quick reply ! But how can we disable certificat verification to allow self-signed ?

Regards. 

2018-05-23 13:20:33.309576657 +0200 test: {"url":"https://someserver.intra/rest/users","status":0,"error":"SSL_connect returned=1 errno=0 state=error: certificate verify failed"}

**Comment by HatsuneMiku3939** [comment]
Hello.

v0.8.1 released with self signed ssl supports.
you can use with ca_file, ca_path options as shown below.

```
<source>
  @type http_pull

  tag test
  url https://someserver.intra/rest/users
  interval 1s

  format none
  status_only true
  ca_path /somewhere/stored/server_cert
  ca_file /somewhere/stored/server_cert/server.crt
</source>
```

OR ignore ssl verification with `verify_ssl false` (not recommended)

```
<source>
  @type http_pull

  tag test
  url https://someserver.intra/rest/users
  interval 1s

  format none
  status_only true
  verify_ssl false
</source>
```

**Comment by mareban** [comment]
Hello,

I've tested with the latest update and it seems better, except that i have a 401 message from our HP Oneview monitoring server !

The api request need an **auth header** and reading the doc, this should be possible with the response_header/request_header !

How can we capture the auth response (response_header) and add this response to other requests (request_header) ??

Thanks for your help.

**Comment by HatsuneMiku3939** [comment]
Hello.

Is your request header value dynamically changed?
Sorry, that feature is not supported.

Maybe this plugin will help you.
> https://docs.fluentd.org/v0.12/articles/in_exec

Thank you for your interest. 
And, I'm sorry that I couldn't help you.

**Comment by mareban** [comment]
Hello, 

reading your doc : 

Req/Resp header options
response_header (section) (optional, default: nil)
The name of **response header for capture**.

request_header (section) (optional, default: nil)
The name, value pair of custom reuqest header.

I thought that you can specify the header to capture in response  and then add to your request ??

Thanks anyway.

Regards

**Comment by HatsuneMiku3939** [comment]
hello.

Adding a static custom request is supported. Capturing a request header is also supported. 

But, capture the request header, add it to the next request is impossible at this time. In current implement, all your request is isolated. There is no way to pass the information to future request.

I'm very sorry for that.
